import { HeroVideo } from "@/components/media/HeroVideo";
import { MediaSlot } from "@/components/media/MediaSlot";
import SiteFooter from "@/components/SiteFooter";
import { pageMeta } from "@/data/siteContent";

export const metadata = pageMeta.developments;

export default function Page() {
  return (
<div id="top" data-screen-label="Developments" style={{position:"relative",background:"#f6f2ea"}}>
  <main>

    <section data-hero="" aria-label="Developments" style={{position:"relative",zIndex:"1"}}>
      <div style={{position:"relative",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",clipPath:"inset(0 round 0 0 min(4.33rem,12vw) min(4.33rem,12vw))"}}>
        <div data-hero-mask="" style={{position:"fixed",top:"0",left:"0",width:"100%",height:"100vh",WebkitMaskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)",maskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)"}}>
          <div data-intro-img="" style={{position:"absolute",inset:"0",transformOrigin:"50% 65%"}}><HeroVideo k="dev" style={{position:"absolute",inset:"0",backgroundImage:"linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}} /></div>
          <div style={{position:"absolute",inset:"0 0 auto 0",height:"13.33rem",backgroundImage:"linear-gradient(#0006,#0000)"}}></div>
          <div style={{position:"absolute",inset:"auto 0 0 0",height:"55%",backgroundImage:"linear-gradient(#1c231f00,#1c231f99)"}}></div>
        </div>
        <div style={{position:"relative",zIndex:"1",height:"100svh",minHeight:"34rem",display:"flex",flexDirection:"column",justifyContent:"flex-end",padding:"0 clamp(1rem,5vw,12rem) min(5rem,16vw)"}}>
          <div style={{display:"flex",flexWrap:"wrap",alignItems:"flex-end",justifyContent:"space-between",gap:"2rem 3rem"}}>
            <div style={{display:"flex",flexDirection:"column",gap:"1.4rem",minWidth:"0"}}>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Developments</span>
              <h1 style={{margin:"0",color:"#f6f2ea",textTransform:"uppercase",fontWeight:"300",fontSize:"min(7rem,11vw,12.5vh)",lineHeight:"0.95",letterSpacing:"-0.03em"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.07em"}}><span data-intro-line="" style={{display:"block"}}>Selected</span></span><span style={{display:"block",overflow:"hidden",paddingBottom:"0.07em"}}><span data-intro-line="" style={{display:"block"}}><em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.08em"}}>developments.</em></span></span></h1>
            </div>
            <div style={{display:"flex",flexDirection:"column",gap:"0.55rem",paddingBottom:"0.6rem",minWidth:"14rem"}}>
              <span data-intro-fade="" style={{display:"block",height:"0.13rem",width:"3rem",background:"#f6f2eab3",marginBottom:"0.6rem"}}></span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Furtado Property</span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Residential development</span>
              <span data-intro-fade="" style={{fontSize:"0.9rem",fontWeight:"500",color:"#b9c0aa",marginTop:"0.4rem"}}>Queensland, Australia</span>
            </div>
          </div>
          <div style={{position:"absolute",left:"0",right:"0",bottom:"1.4rem",display:"flex",justifyContent:"center",pointerEvents:"none"}}>
            <a href="#intro" aria-label="Scroll down" data-intro-fade="" style={{pointerEvents:"auto",display:"flex",alignItems:"center",justifyContent:"center",width:"2.66rem",height:"2.66rem",color:"#f6f2ea",overflow:"hidden"}}><svg viewBox="0 0 10 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"0.66rem",height:"1.2rem",animation:"arrowLoop 2.6s cubic-bezier(.5,1,.89,1) infinite"}}><path d="M5 1v14M1 10.5L5 15l4-4.5"></path></svg></a>
          </div>
        </div>
        <div id="intro" data-hero-content="" style={{position:"relative",zIndex:"1",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(5.5rem,16vw)",display:"flex",flexDirection:"column",gap:"min(2rem,7vw)"}}><span data-r="fade" style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea",letterSpacing:"0.04em"}}>Portfolio</span><h2 data-r="lines" style={{margin:"0",color:"#f6f2ea",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.6rem,7.2vw)",lineHeight:"1.04",letterSpacing:"-0.02em",maxWidth:"80rem"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Two current projects:</span></span><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>one nearing completion <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",fontSize:"1.08em"}}>on the coast,</em></span></span><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>one lodged <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",fontSize:"1.08em"}}>in inner Brisbane.</em></span></span></h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,24rem),1fr))",gap:"2rem 3.33rem",alignItems:"end"}}><p data-r="fade" style={{margin:"0",color:"#f6f2ea",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"36rem",textWrap:"pretty"}}>MIRA Living in Bargara and the West End proposal together show Graham’s development story: site opportunity, product positioning, consultant coordination and delivery to market.</p></div></div>
      </div>
    </section>
    <article style={{position:"relative",zIndex:"2",background:"#f6f2ea",padding:"min(1.6rem,6vw) clamp(1rem,5vw,12rem) min(2rem,7vw)",display:"flex",flexDirection:"column",gap:"min(1.2rem,4.5vw)"}}>
      <div style={{display:"flex",flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",gap:"1rem",borderTop:"0.13rem solid #6f7e6b40",paddingTop:"1.33rem"}}>
        <span style={{display:"flex",gap:"1.2rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}><span>01</span><span>Bargara, Queensland</span></span>
        <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f"}}>Nearing completion</span>
      </div>
      <a href="/developments/mira-living" data-zoom-trigger="" style={{display:"flex",flexDirection:"column",gap:"min(1.4rem,5vw)",color:"#1c231f"}}>
        <h2 data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(10rem,18vw)",lineHeight:"0.86"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}><span style={{backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>MIRA Living</span></span></span></h2>
        <div data-r="img" style={{position:"relative",aspectRatio:"21/9",minHeight:"18rem",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-zoom="" style={{position:"absolute",inset:"0"}}><MediaSlot k="mira.wide" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.06em",textTransform:"uppercase",color:"#f6f2ea"}}>MIRA Living — cinematic image</span></MediaSlot></div></div></div>
      </a>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,24rem),1fr))",gap:"min(1.6rem,5vw) 3.33rem",alignItems:"start"}}><p data-r="fade" style={{margin:"0",textWrap:"pretty",fontSize:"1.13rem",lineHeight:"1.45",color:"#1c231f",maxWidth:"34rem"}}>Boutique oceanfront residential living on the Bargara Esplanade. MIRA Living publicly identifies Graham as its developer, through Furtado Property.</p><div style={{display:"flex",flexDirection:"column",gap:"1.2rem",minWidth:"0"}}><div data-r="group" style={{display:"flex",flexDirection:"column",borderTop:"0.13rem solid #6f7e6b40"}}><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Location</span><span style={{fontWeight:"600",color:"#1c231f"}}>25–27 Esplanade, Bargara</span></div><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Scale</span><span style={{fontWeight:"600",color:"#1c231f"}}>25 residences</span></div><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Status</span><span style={{fontWeight:"600",color:"#1c231f"}}>Under construction; 98% complete (September 2026)</span></div><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Completion</span><span style={{fontWeight:"600",color:"#1c231f"}}>September 2026</span></div></div><a href="/developments/mira-living" style={{alignSelf:"flex-start",display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f",paddingBottom:"0.5rem",background:"linear-gradient(#1c231f,#1c231f) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow gf-btn gf-btn-arrow">Development details <svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a></div></div>
    </article>
    <article style={{position:"relative",zIndex:"2",background:"#f6f2ea",padding:"min(1.6rem,6vw) clamp(1rem,5vw,12rem) min(2rem,7vw)",display:"flex",flexDirection:"column",gap:"min(1.2rem,4.5vw)"}}>
      <div style={{display:"flex",flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",gap:"1rem",borderTop:"0.13rem solid #6f7e6b40",paddingTop:"1.33rem"}}>
        <span style={{display:"flex",gap:"1.2rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}><span>02</span><span>Brisbane, Queensland</span></span>
        <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f"}}>Proposed · DA lodged</span>
      </div>
      <a href="/developments/west-end" data-zoom-trigger="" style={{display:"flex",flexDirection:"column",gap:"min(1.4rem,5vw)",color:"#1c231f"}}>
        <h2 data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(10rem,18vw)",lineHeight:"0.86",textAlign:"right"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}><span style={{backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>West End</span></span></span></h2>
        <div data-r="img" style={{position:"relative",aspectRatio:"21/9",minHeight:"18rem",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-zoom="" style={{position:"absolute",inset:"0"}}><MediaSlot k="we.wide" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.06em",textTransform:"uppercase",color:"#f6f2ea"}}>West End — cinematic image</span></MediaSlot></div></div></div>
      </a>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,24rem),1fr))",gap:"min(1.6rem,5vw) 3.33rem",alignItems:"start"}}><p data-r="fade" style={{margin:"0",textWrap:"pretty",fontSize:"1.13rem",lineHeight:"1.45",color:"#1c231f",maxWidth:"34rem"}}>A 13-storey residential proposal at Wolfe and Greet Streets, lodged with Brisbane City Council in September 2026. A major step up in scale from MIRA Living.</p><div style={{display:"flex",flexDirection:"column",gap:"1.2rem",minWidth:"0"}}><div data-r="group" style={{display:"flex",flexDirection:"column",borderTop:"0.13rem solid #6f7e6b40"}}><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Site</span><span style={{fontWeight:"600",color:"#1c231f"}}>5 Wolfe St &amp; 6–8 Greet St</span></div><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Scale</span><span style={{fontWeight:"600",color:"#1c231f"}}>13 storeys, 113 apartments</span></div><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Architect</span><span style={{fontWeight:"600",color:"#1c231f"}}>MAS Architecture</span></div><div style={{display:"grid",gridTemplateColumns:"8rem minmax(0,1fr)",gap:"1rem",alignItems:"baseline",padding:"0.75rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Status</span><span style={{fontWeight:"600",color:"#1c231f"}}>Lodged; received 9 September 2026</span></div></div><a href="/developments/west-end" style={{alignSelf:"flex-start",display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f",paddingBottom:"0.5rem",background:"linear-gradient(#1c231f,#1c231f) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow gf-btn gf-btn-arrow">Proposal details <svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a></div></div>
    </article>
  </main>
  <SiteFooter />
</div>
  );
}
