import Image from "next/image";
import { MediaSlot } from "@/components/media/MediaSlot";
import SiteFooter from "@/components/SiteFooter";
import { pageMeta } from "@/data/siteContent";

export const metadata = pageMeta.approach;

export default function Page() {
  return (
<div id="top" data-screen-label="Approach" style={{position:"relative",background:"#f6f2ea"}}>
  <main>

    <section data-hero="" aria-label="Development approach" style={{position:"relative",zIndex:"1"}}>
      <div style={{position:"relative",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",clipPath:"inset(0 round 0 0 min(4.33rem,12vw) min(4.33rem,12vw))"}}>
        <div data-hero-mask="" style={{position:"fixed",top:"0",left:"0",width:"100%",height:"100vh",WebkitMaskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)",maskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)"}}>
          <div data-intro-img="" style={{position:"absolute",inset:"0",transformOrigin:"50% 65%"}}><MediaSlot k="app.hero" eager style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",right:"clamp(1rem,5vw,12rem)",top:"auto",bottom:"1.5rem",textAlign:"right",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(22rem,60vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>HERO · LANDSCAPE 16:9 · Concrete structure of an apartment building under construction, clean geometry, long shadows, blue sky. No people</span></MediaSlot></div>
          <div style={{position:"absolute",inset:"0 0 auto 0",height:"13.33rem",backgroundImage:"linear-gradient(#0006,#0000)"}}></div>
          <div style={{position:"absolute",inset:"auto 0 0 0",height:"55%",backgroundImage:"linear-gradient(#1c231f00,#1c231f99)"}}></div>
        </div>
        <div style={{position:"relative",zIndex:"1",height:"100svh",minHeight:"34rem",display:"flex",flexDirection:"column",justifyContent:"flex-end",padding:"0 clamp(1rem,5vw,12rem) min(5rem,16vw)"}}>
          <div style={{display:"flex",flexWrap:"wrap",alignItems:"flex-end",justifyContent:"space-between",gap:"2rem 3rem"}}>
            <div style={{display:"flex",flexDirection:"column",gap:"1.4rem",minWidth:"0"}}>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Development approach</span>
              <h1 style={{margin:"0",color:"#f6f2ea",textTransform:"uppercase",fontWeight:"300",fontSize:"min(7rem,12.5vw,12.5vh)",lineHeight:"0.95",letterSpacing:"-0.03em"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.07em"}}><span data-intro-line="" style={{display:"block"}}>One journey,</span></span><span style={{display:"block",overflow:"hidden",paddingBottom:"0.07em"}}><span data-intro-line="" style={{display:"block"}}>from <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.08em"}}>site</em> to <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.08em"}}>keys.</em></span></span></h1>
            </div>
            <div style={{display:"flex",flexDirection:"column",gap:"0.55rem",paddingBottom:"0.6rem",minWidth:"14rem"}}>
              <span data-intro-fade="" style={{display:"block",height:"0.13rem",width:"3rem",background:"#f6f2eab3",marginBottom:"0.6rem"}}></span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Identify</span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Design</span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Deliver</span>
              <span data-intro-fade="" style={{fontSize:"0.9rem",fontWeight:"500",color:"#b9c0aa",marginTop:"0.4rem"}}>Six stages</span>
            </div>
          </div>
          <div style={{position:"absolute",left:"0",right:"0",bottom:"1.4rem",display:"flex",justifyContent:"center",pointerEvents:"none"}}>
            <a href="#intro" aria-label="Scroll down" data-intro-fade="" style={{pointerEvents:"auto",display:"flex",alignItems:"center",justifyContent:"center",width:"2.66rem",height:"2.66rem",color:"#f6f2ea",overflow:"hidden"}}><svg viewBox="0 0 10 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"0.66rem",height:"1.2rem",animation:"arrowLoop 2.6s cubic-bezier(.5,1,.89,1) infinite"}}><path d="M5 1v14M1 10.5L5 15l4-4.5"></path></svg></a>
          </div>
        </div>
        <div id="intro" data-hero-content="" style={{position:"relative",zIndex:"1",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(5.5rem,16vw)",display:"flex",flexDirection:"column",gap:"min(2rem,7vw)"}}><span data-r="fade" style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea",letterSpacing:"0.04em"}}>Approach</span><h2 data-r="lines" style={{margin:"0",color:"#f6f2ea",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.6rem,7.2vw)",lineHeight:"1.04",letterSpacing:"-0.02em",maxWidth:"80rem"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Each stage builds on the last,</span></span><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>with <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",fontSize:"1.08em"}}>one vision</em> held throughout.</span></span></h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,24rem),1fr))",gap:"2rem 3.33rem",alignItems:"end"}}><p data-r="fade" style={{margin:"0",color:"#f6f2ea",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"36rem",textWrap:"pretty"}}>Furtado Property describes its process from site identification through to handing over the keys, working with experienced architects and designers and specialist consultants along the way.</p></div></div>
      </div>
    </section>
    <section data-steps="" id="stages" aria-label="Development stages" style={{position:"relative",zIndex:"2",height:"510vh",background:"#f6f2ea"}}>
      <div style={{position:"sticky",top:"0",height:"100svh",overflow:"hidden",display:"flex",flexDirection:"column",justifyContent:"center",gap:"min(2.4rem,5vh)",padding:"min(4rem,10vh) clamp(1rem,5vw,12rem) min(1.5rem,3vh)"}}>
        <span aria-hidden="true" style={{position:"absolute",left:"0",top:"0",bottom:"0",width:"0.26rem",background:"#6f7e6b40"}}></span>
        <span data-steps-bar="" aria-hidden="true" style={{position:"absolute",left:"0",top:"0",bottom:"0",width:"0.26rem",background:"#6f7e6b",transformOrigin:"50% 0%",transform:"scaleY(0)"}}></span>
        <div style={{display:"flex",flexWrap:"wrap",alignItems:"center",gap:"1.5rem min(5rem,6vw)"}}>
          <div aria-hidden="true" style={{flex:"0 0 auto",overflow:"hidden",height:"1em",fontSize:"min(15rem,30vw,32vh)",lineHeight:"1",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",letterSpacing:"-0.03em"}}>
            <div data-steps-roll="" style={{display:"flex",flexDirection:"column"}}><span style={{display:"block",height:"1em",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>01</span><span style={{display:"block",height:"1em",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>02</span><span style={{display:"block",height:"1em",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>03</span><span style={{display:"block",height:"1em",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>04</span><span style={{display:"block",height:"1em",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>05</span><span style={{display:"block",height:"1em",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>06</span></div>
          </div>
          <div style={{flex:"1 1 34rem",minWidth:"0",display:"grid"}}>
            <div data-step-panel="" style={{gridArea:"1/1",display:"flex",flexWrap:"wrap",alignItems:"center",gap:"1.5rem min(4rem,4vw)"}}>
              <div style={{flex:"1 1 18rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Stage 01 / 06</span>
                <h2 style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(4.4rem,12vw,9vh)",lineHeight:"0.95",color:"#1c231f"}}>Identify</h2>
                <p style={{margin:"0",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"30rem",textWrap:"pretty"}}>Every project starts with finding the right site: a location with potential, and a gap in the market it can fill.</p>
              </div>
              <div data-step-img="" style={{flex:"1.3 1 22rem",position:"relative",height:"clamp(16rem,62vh,44rem)",borderRadius:"1rem",overflow:"hidden"}}><MediaSlot k="app.1" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>LANDSCAPE 4:3 · Vacant coastal or inner-city site seen from the street: fence, old sign, mature tree, morning light</span></MediaSlot></div>
            </div>
            <div data-step-panel="" style={{gridArea:"1/1",display:"flex",flexWrap:"wrap",alignItems:"center",gap:"1.5rem min(4rem,4vw)"}}>
              <div style={{flex:"1 1 18rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Stage 02 / 06</span>
                <h2 style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(4.4rem,12vw,9vh)",lineHeight:"0.95",color:"#1c231f"}}>Assess</h2>
                <p style={{margin:"0",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"30rem",textWrap:"pretty"}}>A high-level read of site potential, market fit and product direction before a project progresses.</p>
              </div>
              <div data-step-img="" style={{flex:"1.3 1 22rem",position:"relative",height:"clamp(16rem,62vh,44rem)",borderRadius:"1rem",overflow:"hidden"}}><MediaSlot k="app.2" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>LANDSCAPE 4:3 · Site survey: printed plans and tablet on a car bonnet, block visible behind, overcast light</span></MediaSlot></div>
            </div>
            <div data-step-panel="" style={{gridArea:"1/1",display:"flex",flexWrap:"wrap",alignItems:"center",gap:"1.5rem min(4rem,4vw)"}}>
              <div style={{flex:"1 1 18rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Stage 03 / 06</span>
                <h2 style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(4.4rem,12vw,9vh)",lineHeight:"0.95",color:"#1c231f"}}>Envision</h2>
                <p style={{margin:"0",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"30rem",textWrap:"pretty"}}>Defining the residential offer: who it is for, how it is positioned and how people will live in it.</p>
              </div>
              <div data-step-img="" style={{flex:"1.3 1 22rem",position:"relative",height:"clamp(16rem,62vh,44rem)",borderRadius:"1rem",overflow:"hidden"}}><MediaSlot k="app.3" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.1) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>LANDSCAPE 4:3 · Material mood board: sand-coloured brick, pale oak, travertine, linen. Overhead, soft light</span></MediaSlot></div>
            </div>
            <div data-step-panel="" style={{gridArea:"1/1",display:"flex",flexWrap:"wrap",alignItems:"center",gap:"1.5rem min(4rem,4vw)"}}>
              <div style={{flex:"1 1 18rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Stage 04 / 06</span>
                <h2 style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(4.4rem,12vw,9vh)",lineHeight:"0.95",color:"#1c231f"}}>Design</h2>
                <p style={{margin:"0",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"30rem",textWrap:"pretty"}}>Working with experienced architects and designers on buildings intended to remain relevant over time.</p>
              </div>
              <div data-step-img="" style={{flex:"1.3 1 22rem",position:"relative",height:"clamp(16rem,62vh,44rem)",borderRadius:"1rem",overflow:"hidden"}}><MediaSlot k="app.4" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>LANDSCAPE 4:3 · Architectural drawings and a white study model on a desk, afternoon light through blinds</span></MediaSlot></div>
            </div>
            <div data-step-panel="" style={{gridArea:"1/1",display:"flex",flexWrap:"wrap",alignItems:"center",gap:"1.5rem min(4rem,4vw)"}}>
              <div style={{flex:"1 1 18rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Stage 05 / 06</span>
                <h2 style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(4.4rem,12vw,9vh)",lineHeight:"0.95",color:"#1c231f"}}>Develop</h2>
                <p style={{margin:"0",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"30rem",textWrap:"pretty"}}>Coordinating planners, engineers, builders and specialists while holding the original development vision.</p>
              </div>
              <div data-step-img="" style={{flex:"1.3 1 22rem",position:"relative",height:"clamp(16rem,62vh,44rem)",borderRadius:"1rem",overflow:"hidden"}}><MediaSlot k="app.5" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>LANDSCAPE 4:3 · Construction progress: concrete slab pour with workers, crane above, bright daylight</span></MediaSlot></div>
            </div>
            <div data-step-panel="" style={{gridArea:"1/1",display:"flex",flexWrap:"wrap",alignItems:"center",gap:"1.5rem min(4rem,4vw)"}}>
              <div style={{flex:"1 1 18rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Stage 06 / 06</span>
                <h2 style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(4.4rem,12vw,9vh)",lineHeight:"0.95",color:"#1c231f"}}>Deliver</h2>
                <p style={{margin:"0",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"30rem",textWrap:"pretty"}}>Bringing the finished homes to market, through to handing over the keys.</p>
              </div>
              <div data-step-img="" style={{flex:"1.3 1 22rem",position:"relative",height:"clamp(16rem,62vh,44rem)",borderRadius:"1rem",overflow:"hidden"}}><MediaSlot k="app.6" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.1) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>LANDSCAPE 4:3 · Completed residence at twilight: interior lights on, landscaping settled, quiet street</span></MediaSlot></div>
            </div>
          </div>
        </div>
        <div style={{display:"flex",flexWrap:"wrap",gap:"0.4rem 1.6rem",borderTop:"0.13rem solid #6f7e6b40",paddingTop:"1rem"}}>
          <button type="button" data-step-dot="" aria-label="Stage 1: Identify" style={{display:"flex",gap:"0.5rem",background:"none",border:"0",padding:"0.3rem 0",cursor:"pointer",font:"inherit",fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#5f665f",opacity:"0.35",transition:"opacity .4s,color .4s"}}><span>01</span><span>Identify</span></button><button type="button" data-step-dot="" aria-label="Stage 2: Assess" style={{display:"flex",gap:"0.5rem",background:"none",border:"0",padding:"0.3rem 0",cursor:"pointer",font:"inherit",fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#5f665f",opacity:"0.35",transition:"opacity .4s,color .4s"}}><span>02</span><span>Assess</span></button><button type="button" data-step-dot="" aria-label="Stage 3: Envision" style={{display:"flex",gap:"0.5rem",background:"none",border:"0",padding:"0.3rem 0",cursor:"pointer",font:"inherit",fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#5f665f",opacity:"0.35",transition:"opacity .4s,color .4s"}}><span>03</span><span>Envision</span></button><button type="button" data-step-dot="" aria-label="Stage 4: Design" style={{display:"flex",gap:"0.5rem",background:"none",border:"0",padding:"0.3rem 0",cursor:"pointer",font:"inherit",fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#5f665f",opacity:"0.35",transition:"opacity .4s,color .4s"}}><span>04</span><span>Design</span></button><button type="button" data-step-dot="" aria-label="Stage 5: Develop" style={{display:"flex",gap:"0.5rem",background:"none",border:"0",padding:"0.3rem 0",cursor:"pointer",font:"inherit",fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#5f665f",opacity:"0.35",transition:"opacity .4s,color .4s"}}><span>05</span><span>Develop</span></button><button type="button" data-step-dot="" aria-label="Stage 6: Deliver" style={{display:"flex",gap:"0.5rem",background:"none",border:"0",padding:"0.3rem 0",cursor:"pointer",font:"inherit",fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#5f665f",opacity:"0.35",transition:"opacity .4s,color .4s"}}><span>06</span><span>Deliver</span></button>
        </div>
      </div>
    </section><section id="constants" style={{position:"relative",zIndex:"2",background:"#eee9df",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)"}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,22rem),1fr))",gap:"min(2.4rem,7vw) 3.33rem",marginBottom:"min(4rem,12vw)"}}><div style={{display:"flex",flexDirection:"column",gap:"1.66rem",minWidth:"0"}}><h2 id="const-h" data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.06rem,11vw)",lineHeight:"0.95"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.1em"}}><span data-line="" style={{display:"block",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>What stays constant.</span></span></h2></div><p data-r="fade" style={{margin:"0",textWrap:"pretty",maxWidth:"30rem",alignSelf:"end"}}>Graham’s public development approach places strong emphasis on four things, whatever the scale of the project.</p></div>
<div data-r="group" data-constants="" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,13rem),1fr))",gap:"2.5rem 2rem",alignItems:"start"}}><div tabIndex={0} style={{position:"relative",display:"flex",flexDirection:"column",gap:"0.8rem",paddingTop:"1.33rem",borderTop:"0.13rem solid #6f7e6b40",cursor:"default",outline:"none",transition:"transform .7s cubic-bezier(.25,1,.5,1)"}} className="hv-lift fc-lift">
  <span aria-hidden="true" style={{position:"absolute",left:"0",top:"-0.13rem",height:"0.13rem",width:"100%",background:"#6f7e6b",transform:"scaleX(0)",transformOrigin:"0 50%",transition:"transform .8s cubic-bezier(.25,1,.5,1)"}} data-const-bar=""></span>
  <span style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(2.4rem,9vw)",lineHeight:"1",color:"#6f7e6b",transition:"color .4s"}}>01</span>
  <h3 style={{margin:"0",fontSize:"1.33rem",fontWeight:"600",color:"#1c231f"}}>Location</h3>
  <p style={{margin:"0",textWrap:"pretty"}}>Sites chosen for their potential and their fit with the market.</p>
  <div data-const-img="" style={{position:"relative",marginTop:"0.6rem",height:"0",borderRadius:"0.8rem",overflow:"hidden",opacity:"0",transition:"height .8s cubic-bezier(.25,1,.5,1),opacity .6s",background:"#b9c0aa"}}><Image src="/media/west-end/we-10.webp" alt="" loading="lazy" style={{position:"absolute",inset:"0",width:"100%",height:"100%",objectFit:"cover",transform:"scale(1.08)",transition:"transform 1.4s cubic-bezier(.25,1,.5,1)"}} fill sizes="(max-width: 767px) 100vw, 30vw" /></div>
</div><div tabIndex={0} style={{position:"relative",display:"flex",flexDirection:"column",gap:"0.8rem",paddingTop:"1.33rem",borderTop:"0.13rem solid #6f7e6b40",cursor:"default",outline:"none",transition:"transform .7s cubic-bezier(.25,1,.5,1)"}} className="hv-lift fc-lift">
  <span aria-hidden="true" style={{position:"absolute",left:"0",top:"-0.13rem",height:"0.13rem",width:"100%",background:"#6f7e6b",transform:"scaleX(0)",transformOrigin:"0 50%",transition:"transform .8s cubic-bezier(.25,1,.5,1)"}} data-const-bar=""></span>
  <span style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(2.4rem,9vw)",lineHeight:"1",color:"#6f7e6b",transition:"color .4s"}}>02</span>
  <h3 style={{margin:"0",fontSize:"1.33rem",fontWeight:"600",color:"#1c231f"}}>Enduring design</h3>
  <p style={{margin:"0",textWrap:"pretty"}}>Buildings designed with experienced architects to remain relevant over time.</p>
  <div data-const-img="" style={{position:"relative",marginTop:"0.6rem",height:"0",borderRadius:"0.8rem",overflow:"hidden",opacity:"0",transition:"height .8s cubic-bezier(.25,1,.5,1),opacity .6s",background:"#b9c0aa"}}><Image src="/media/west-end/we-08.webp" alt="" loading="lazy" style={{position:"absolute",inset:"0",width:"100%",height:"100%",objectFit:"cover",transform:"scale(1.08)",transition:"transform 1.4s cubic-bezier(.25,1,.5,1)"}} fill sizes="(max-width: 767px) 100vw, 30vw" /></div>
</div><div tabIndex={0} style={{position:"relative",display:"flex",flexDirection:"column",gap:"0.8rem",paddingTop:"1.33rem",borderTop:"0.13rem solid #6f7e6b40",cursor:"default",outline:"none",transition:"transform .7s cubic-bezier(.25,1,.5,1)"}} className="hv-lift fc-lift">
  <span aria-hidden="true" style={{position:"absolute",left:"0",top:"-0.13rem",height:"0.13rem",width:"100%",background:"#6f7e6b",transform:"scaleX(0)",transformOrigin:"0 50%",transition:"transform .8s cubic-bezier(.25,1,.5,1)"}} data-const-bar=""></span>
  <span style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(2.4rem,9vw)",lineHeight:"1",color:"#6f7e6b",transition:"color .4s"}}>03</span>
  <h3 style={{margin:"0",fontSize:"1.33rem",fontWeight:"600",color:"#1c231f"}}>Quality delivery</h3>
  <p style={{margin:"0",textWrap:"pretty"}}>Lasting workmanship, carried through construction to completion.</p>
  <div data-const-img="" style={{position:"relative",marginTop:"0.6rem",height:"0",borderRadius:"0.8rem",overflow:"hidden",opacity:"0",transition:"height .8s cubic-bezier(.25,1,.5,1),opacity .6s",background:"#b9c0aa"}}><Image src="/media/mira/mira-01.webp" alt="" loading="lazy" style={{position:"absolute",inset:"0",width:"100%",height:"100%",objectFit:"cover",transform:"scale(1.08)",transition:"transform 1.4s cubic-bezier(.25,1,.5,1)"}} fill sizes="(max-width: 767px) 100vw, 30vw" /></div>
</div><div tabIndex={0} style={{position:"relative",display:"flex",flexDirection:"column",gap:"0.8rem",paddingTop:"1.33rem",borderTop:"0.13rem solid #6f7e6b40",cursor:"default",outline:"none",transition:"transform .7s cubic-bezier(.25,1,.5,1)"}} className="hv-lift fc-lift">
  <span aria-hidden="true" style={{position:"absolute",left:"0",top:"-0.13rem",height:"0.13rem",width:"100%",background:"#6f7e6b",transform:"scaleX(0)",transformOrigin:"0 50%",transition:"transform .8s cubic-bezier(.25,1,.5,1)"}} data-const-bar=""></span>
  <span style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(2.4rem,9vw)",lineHeight:"1",color:"#6f7e6b",transition:"color .4s"}}>04</span>
  <h3 style={{margin:"0",fontSize:"1.33rem",fontWeight:"600",color:"#1c231f"}}>The people who live there</h3>
  <p style={{margin:"0",textWrap:"pretty"}}>The finished home and the experience of living in it.</p>
  <div data-const-img="" style={{position:"relative",marginTop:"0.6rem",height:"0",borderRadius:"0.8rem",overflow:"hidden",opacity:"0",transition:"height .8s cubic-bezier(.25,1,.5,1),opacity .6s",background:"#b9c0aa"}}><Image src="/media/mira/mira-05.webp" alt="" loading="lazy" style={{position:"absolute",inset:"0",width:"100%",height:"100%",objectFit:"cover",transform:"scale(1.08)",transition:"transform 1.4s cubic-bezier(.25,1,.5,1)"}} fill sizes="(max-width: 767px) 100vw, 30vw" /></div>
</div></div></section><section id="practice" style={{position:"relative",zIndex:"2",background:"#f6f2ea",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)"}}><div style={{display:"flex",flexWrap:"wrap",alignItems:"flex-end",justifyContent:"space-between",gap:"1.5rem 3rem",marginBottom:"min(2rem,7vw)"}}><h2 id="prac-h" data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.06rem,11vw)",lineHeight:"0.95"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.1em"}}><span data-line="" style={{display:"block",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>The approach in practice.</span></span></h2><a href="/developments" style={{alignSelf:"flex-start",display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f",paddingBottom:"0.5rem",background:"linear-gradient(#1c231f,#1c231f) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow">All developments <svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,22rem),1fr))",gap:"1rem"}}><a href="/developments/mira-living" data-zoom-trigger="" style={{position:"relative",display:"flex",flexDirection:"column",minHeight:"min(34rem,110vw)",color:"#f6f2ea",borderRadius:"1rem",overflow:"hidden"}}>
  <div style={{position:"absolute",inset:"0",overflow:"hidden",background:"#b9c0aa"}}><div data-zoom="" style={{position:"absolute",inset:"0"}}><MediaSlot k="mira.hero" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}></MediaSlot></div><span style={{position:"absolute",zIndex:"2",top:"1.33rem",left:"1.33rem",padding:"0.53rem 0.8rem",borderRadius:"999px",background:"#1c231f66",WebkitBackdropFilter:"blur(6px)",backdropFilter:"blur(6px)",fontSize:"0.8rem",fontWeight:"700",lineHeight:"1"}}>01</span></div>
  <div style={{position:"relative",zIndex:"1",marginTop:"auto",display:"flex",flexDirection:"column",gap:"1.33rem",padding:"min(9rem,30vw) 1.66rem 2.2rem 1.66rem",backgroundImage:"linear-gradient(180deg,#1c231f00 0%,#1c231fb3 45%,#1c231fe6 100%)"}}>
    <div style={{display:"flex",flexDirection:"column",gap:"0.4rem"}}><span style={{fontSize:"1.8rem",fontWeight:"600",lineHeight:"1.2"}}>MIRA Living</span><span style={{opacity:"0.9"}}>Bargara, Queensland</span></div>
    <div style={{display:"flex",flexWrap:"wrap",gap:"0.66rem 1.33rem"}}><span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>25 residences</span><span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>Completion September 2026</span></div>
    <span style={{alignSelf:"flex-start",marginTop:"auto",display:"inline-flex",border:"0.13rem solid #f6f2ea",borderRadius:"999px",padding:"0.84em 2.6em",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase"}}>Development details</span>
  </div>
</a><a href="/developments/west-end" data-zoom-trigger="" style={{position:"relative",display:"flex",flexDirection:"column",minHeight:"min(34rem,110vw)",color:"#f6f2ea",borderRadius:"1rem",overflow:"hidden"}}>
  <div style={{position:"absolute",inset:"0",overflow:"hidden",background:"#b9c0aa"}}><div data-zoom="" style={{position:"absolute",inset:"0"}}><MediaSlot k="we.hero" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}></MediaSlot></div><span style={{position:"absolute",zIndex:"2",top:"1.33rem",left:"1.33rem",padding:"0.53rem 0.8rem",borderRadius:"999px",background:"#1c231f66",WebkitBackdropFilter:"blur(6px)",backdropFilter:"blur(6px)",fontSize:"0.8rem",fontWeight:"700",lineHeight:"1"}}>02</span></div>
  <div style={{position:"relative",zIndex:"1",marginTop:"auto",display:"flex",flexDirection:"column",gap:"1.33rem",padding:"min(9rem,30vw) 1.66rem 2.2rem 1.66rem",backgroundImage:"linear-gradient(180deg,#1c231f00 0%,#1c231fb3 45%,#1c231fe6 100%)"}}>
    <div style={{display:"flex",flexDirection:"column",gap:"0.4rem"}}><span style={{fontSize:"1.8rem",fontWeight:"600",lineHeight:"1.2"}}>West End</span><span style={{opacity:"0.9"}}>Brisbane, Queensland</span></div>
    <div style={{display:"flex",flexWrap:"wrap",gap:"0.66rem 1.33rem"}}><span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>113 apartments proposed</span><span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>DA lodged September 2026</span></div>
    <span style={{alignSelf:"flex-start",marginTop:"auto",display:"inline-flex",border:"0.13rem solid #f6f2ea",borderRadius:"999px",padding:"0.84em 2.6em",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase"}}>Proposal details</span>
  </div>
</a></div></section>
  </main>
  <SiteFooter />
</div>
  );
}
