import { MediaSlot } from "@/components/media/MediaSlot";
import SiteFooter from "@/components/SiteFooter";
import { pageMeta } from "@/data/siteContent";

export const metadata = pageMeta.home;

export default function Page() {
  return (
<div id="top" data-screen-label="Home" style={{position:"relative",background:"#f6f2ea"}}>
  <main>
    <section data-hero="" aria-label="Introduction" style={{position:"relative",zIndex:"1"}}>
      <div style={{position:"relative",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",clipPath:"inset(0 round 0 0 min(4.33rem,12vw) min(4.33rem,12vw))"}}>
        <div data-hero-mask="" style={{position:"fixed",top:"0",left:"0",width:"100%",height:"100vh",WebkitMaskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)",maskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)"}}>
          <div data-intro-img="" style={{position:"absolute",inset:"0",transformOrigin:"50% 65%"}}>
            <MediaSlot k="home.hero" eager style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",right:"clamp(1rem,5vw,12rem)",top:"auto",bottom:"1.5rem",textAlign:"right",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",opacity:"0.8",maxWidth:"min(22rem,60vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>HERO · LANDSCAPE 16:9 · Modern Queensland coastal residence at dusk, low sun, warm timber + off-white render, sub-tropical planting, ocean horizon behind. Wide cinematic shot, no people, no text</span></MediaSlot>
          </div>
          <div style={{position:"absolute",inset:"0 0 auto 0",height:"13.33rem",backgroundImage:"linear-gradient(#0006,#0000)"}}></div>
          <div style={{position:"absolute",inset:"auto 0 0 0",height:"55%",backgroundImage:"linear-gradient(#1c231f00,#1c231f99)"}}></div>
        </div>

        <div style={{position:"relative",zIndex:"1",height:"100svh",minHeight:"34rem",display:"flex",flexDirection:"column",justifyContent:"flex-end",padding:"0 clamp(1rem,5vw,12rem) min(5rem,16vw)"}}>
          <div style={{display:"flex",flexWrap:"wrap",alignItems:"flex-end",justifyContent:"space-between",gap:"2rem 3rem"}}>
            <h1 data-hero-name="" style={{margin:"0",color:"#f6f2ea",fontWeight:"300",textTransform:"uppercase",fontSize:"min(9.4rem,18vw,22vh)",lineHeight:"0.9",letterSpacing:"-0.035em"}}>
              <span style={{display:"block",overflow:"hidden"}}><span data-intro-line="" style={{display:"block"}}>Graham</span></span>
              <span style={{display:"block",overflow:"hidden",paddingBottom:"0.08em"}}><span data-intro-line="" style={{display:"block",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",letterSpacing:"-0.01em",paddingRight:"0.06em"}}>Furtado</span></span>
            </h1>
            <div style={{display:"flex",flexDirection:"column",gap:"0.55rem",paddingBottom:"0.6rem",minWidth:"14rem"}}>
              <span data-intro-fade="" style={{display:"block",height:"0.13rem",width:"3rem",background:"#f6f2eab3",marginBottom:"0.6rem"}}></span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Property Developer</span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Real Estate</span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Development Advisory</span>
              <span data-intro-fade="" style={{fontSize:"0.9rem",fontWeight:"500",color:"#b9c0aa",marginTop:"0.4rem"}}>Queensland, Australia</span>
            </div>
          </div>
          <div style={{position:"absolute",left:"0",right:"0",bottom:"1.4rem",display:"flex",justifyContent:"center",pointerEvents:"none"}}>
            <a href="#intro" aria-label="Scroll to introduction" data-intro-fade="" style={{pointerEvents:"auto",display:"flex",alignItems:"center",justifyContent:"center",width:"2.66rem",height:"2.66rem",color:"#f6f2ea",overflow:"hidden"}}>
              <svg viewBox="0 0 10 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"0.66rem",height:"1.2rem",animation:"arrowLoop 2.6s cubic-bezier(.5,1,.89,1) infinite"}}><path d="M5 1v14M1 10.5L5 15l4-4.5"></path></svg>
            </a>
          </div>
        </div>

        <div id="intro" data-hero-content="" style={{position:"relative",zIndex:"1",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(5.5rem,16vw)",display:"flex",flexDirection:"column",gap:"min(3.5rem,11vw)"}}>
          <span data-r="fade" style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea",letterSpacing:"0.04em"}}>Profile</span>
          <h2 data-r="lines" style={{margin:"0",color:"#f6f2ea",fontWeight:"400",textTransform:"uppercase",fontSize:"min(4.4rem,8.2vw)",lineHeight:"1.02",letterSpacing:"-0.02em",maxWidth:"82rem"}}>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Around three decades</span></span>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>in <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",fontSize:"1.08em"}}>Queensland property.</em></span></span>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>A <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",fontSize:"1.08em"}}>considered</em> approach</span></span>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>to residential development.</span></span>
          </h2>
          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,24rem),1fr))",gap:"2.5rem 3.33rem",alignItems:"end"}}>
            <p data-r="fade" style={{margin:"0",color:"#f6f2ea",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"34rem",textWrap:"pretty"}}>Graham Furtado is a Queensland property developer and experienced real-estate professional. Through Furtado Property, he guides residential projects from site opportunity and early strategy through design, consultant coordination, construction and market delivery.</p>
            <div data-r="fade" data-delay="0.15" style={{display:"flex",flexWrap:"wrap",gap:"1.5rem 2.66rem",justifyContent:"flex-start"}}>
              <a href="#developments" style={{display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea",paddingBottom:"0.5rem",background:"linear-gradient(#f6f2ea,#f6f2ea) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow-ink gf-btn gf-btn-arrow">Selected developments <svg viewBox="0 0 10 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"0.55rem",height:"0.9rem"}}><path d="M5 1v14M1 10.5L5 15l4-4.5"></path></svg></a>
              <a href="/about" style={{display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea",paddingBottom:"0.5rem",background:"linear-gradient(#f6f2eab3,#f6f2eab3) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow-ink gf-btn gf-btn-arrow">Graham’s story <svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section id="profile" aria-labelledby="profile-h" style={{position:"relative",zIndex:"2",background:"#f6f2ea",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)"}}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,26rem),1fr))",gap:"min(2.4rem,7vw) 3.33rem",alignItems:"end"}}>
        <a href="/about" data-zoom-trigger="" style={{position:"relative",display:"block",width:"100%",maxWidth:"32rem",borderRadius:"1rem",overflow:"hidden"}}>
          <div data-r="img" style={{position:"relative",height:"min(33rem,130vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}>
            <div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-zoom="" style={{position:"absolute",inset:"0"}}>
              <MediaSlot k="home.portrait" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",top:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>PORTRAIT 3:4 · Graham Furtado, editorial half-length portrait on a development site or in front of concrete/timber architecture. Natural side light, neutral tones, relaxed, looking off camera</span></MediaSlot>
            </div></div>
          </div>
          <div style={{position:"absolute",left:"0",right:"0",bottom:"0",display:"flex",flexDirection:"column",gap:"1rem",padding:"2rem 3.33rem 2.2rem 2.33rem",borderRadius:"1rem",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)"}}>
            <span style={{fontSize:"1.8rem",fontWeight:"600",lineHeight:"1.1",color:"#f6f2ea"}}>Graham<br />Furtado</span>
            <span style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1.3",textTransform:"uppercase",color:"#f6f2ea"}}>Property Developer · Real Estate Professional</span>
          </div>
        </a>
        <div style={{display:"flex",flexDirection:"column",gap:"2rem",paddingBottom:"0.5rem"}}>
          <h2 id="profile-h" data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.06rem,11vw)",lineHeight:"0.95"}}>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.1em"}}><span data-line="" style={{display:"block",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>Profile.</span></span>
          </h2>
          <div data-r="group" style={{display:"flex",flexDirection:"column",gap:"0.8rem",maxWidth:"34rem"}}>
            <p style={{margin:"0",fontSize:"1.13rem",lineHeight:"1.45",color:"#1c231f",textWrap:"pretty"}}>Graham’s background is in Brisbane real estate, where industry coverage places him among the city’s long-time agents, with around thirty years of experience.</p>
            <p style={{margin:"0",textWrap:"pretty"}}>That market knowledge now underpins his work as a residential developer. His development story currently spans MIRA Living, a boutique oceanfront project in Bargara, and a lodged 113-apartment proposal in West End, Brisbane.</p>
          </div>
          <div data-r="group" style={{display:"flex",flexDirection:"column"}}>
            <div style={{display:"grid",gridTemplateColumns:"8rem 1fr",gap:"1rem",alignItems:"baseline",padding:"1rem 0",borderTop:"0.13rem solid #6f7e6b40",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Based in</span><span style={{fontWeight:"600",color:"#1c231f"}}>Brisbane, Queensland</span></div>
            <div style={{display:"grid",gridTemplateColumns:"8rem 1fr",gap:"1rem",alignItems:"baseline",padding:"1rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Company</span><span style={{fontWeight:"600",color:"#1c231f"}}>Furtado Property</span></div>
            <div style={{display:"grid",gridTemplateColumns:"8rem 1fr",gap:"1rem",alignItems:"baseline",padding:"1rem 0",borderBottom:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b"}}>Focus</span><span style={{fontWeight:"600",color:"#1c231f"}}>Residential development, South-East Queensland</span></div>
          </div>
          <a data-r="fade" href="/about" style={{alignSelf:"flex-start",display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f",paddingBottom:"0.5rem",background:"linear-gradient(#1c231f,#1c231f) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow gf-btn gf-btn-arrow">About Graham <svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
        </div>
      </div>
    </section>

    <section id="developments" aria-labelledby="dev-h" style={{position:"relative",zIndex:"2",background:"#f6f2ea"}}>
      <div style={{display:"flex",flexWrap:"wrap",alignItems:"flex-end",justifyContent:"space-between",gap:"1.5rem 3rem",padding:"min(3rem,10vw) clamp(1rem,5vw,12rem) min(3.5rem,10vw)"}}>
        <h2 id="dev-h" data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.06rem,11vw)",lineHeight:"0.95"}}>
          <span style={{display:"block",overflow:"hidden",paddingBottom:"0.1em"}}><span data-line="" style={{display:"block",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>Developments.</span></span>
        </h2>
        <p data-r="fade" style={{margin:"0",maxWidth:"26rem",textWrap:"pretty"}}>Two current Furtado Property projects: a boutique coastal residence in Bargara, and a lodged inner-city proposal in West End.</p>
      </div>
      <div data-stack="">
        <a href="/developments/mira-living" data-stack-card="" aria-label="MIRA Living, Bargara — view development" style={{position:"sticky",top:"0",display:"block",height:"100svh",minHeight:"34rem",color:"#f6f2ea"}}>
          <div data-stack-inner="" style={{position:"absolute",inset:"0",overflow:"hidden",borderRadius:"min(4.33rem,12vw) min(4.33rem,12vw) 0 0",transformOrigin:"50% 0%",background:"#1c231f"}}>
            <div data-parallax="8" style={{position:"absolute",inset:"0",overflow:"hidden"}}>
              <div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}>
                <MediaSlot k="mira.hero" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.06) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 45%,#6b7767 100%)"}}><span data-ph-label="" style={{position:"absolute",right:"clamp(1rem,5vw,12rem)",top:"14%",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.06em",textTransform:"uppercase",color:"#f6f2ea"}}>MIRA Living — exterior photography / render</span></MediaSlot>
              </div>
            </div>
            <div style={{position:"absolute",inset:"0",backgroundImage:"linear-gradient(180deg,#1c231f33 0%,#1c231f00 30%,#1c231f00 45%,#1c231fb3 100%)"}}></div>
            <div data-stack-shade="" style={{position:"absolute",inset:"0",background:"#1c231f",opacity:"0"}}></div>
            <div style={{position:"absolute",inset:"0",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"min(2.33rem,6vw) clamp(1rem,5vw,12rem) min(3rem,10vw)"}}>
              <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem"}}>
                <span style={{padding:"0.53rem 0.8rem",borderRadius:"999px",background:"#1c231f66",WebkitBackdropFilter:"blur(6px)",backdropFilter:"blur(6px)",fontSize:"0.8rem",fontWeight:"700",lineHeight:"1"}}>01</span>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",lineHeight:"1"}}>Nearing completion</span>
              </div>
              <div style={{display:"flex",flexDirection:"column",gap:"1.66rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea"}}>Bargara, Queensland</span>
                <span style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(9rem,17vw)",lineHeight:"0.88",letterSpacing:"-0.01em"}}>MIRA Living</span>
                <div style={{display:"flex",flexWrap:"wrap",alignItems:"center",justifyContent:"space-between",gap:"1.2rem 2rem",paddingTop:"1.4rem",borderTop:"0.13rem solid #f6f2ea66"}}>
                  <div style={{display:"flex",flexWrap:"wrap",gap:"0.66rem 1.8rem"}}>
                    <span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>25 residences</span>
                    <span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>Boutique oceanfront apartments</span>
                    <span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>Completion September 2026</span>
                  </div>
                  <span style={{display:"inline-flex",alignItems:"center",border:"0.13rem solid #f6f2ea",borderRadius:"999px",padding:"0.84em 2.6em",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase"}}>View development</span>
                </div>
              </div>
            </div>
          </div>
        </a>
        <div data-stack-hold="" aria-hidden="true" style={{height:"70svh"}}></div>
        <a href="/developments/west-end" data-stack-card="" aria-label="West End, Brisbane — view proposal" style={{position:"sticky",top:"0",display:"block",height:"100svh",minHeight:"34rem",color:"#f6f2ea"}}>
          <div data-stack-inner="" style={{position:"absolute",inset:"0",overflow:"hidden",borderRadius:"min(4.33rem,12vw) min(4.33rem,12vw) 0 0",transformOrigin:"50% 0%",background:"#1c231f"}}>
            <div data-parallax="8" style={{position:"absolute",inset:"0",overflow:"hidden"}}>
              <div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}>
                <MediaSlot k="we.hero" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",right:"clamp(1rem,5vw,12rem)",top:"14%",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.06em",textTransform:"uppercase",color:"#f6f2ea"}}>West End — architectural render (MAS Architecture)</span></MediaSlot>
              </div>
            </div>
            <div style={{position:"absolute",inset:"0",backgroundImage:"linear-gradient(180deg,#1c231f33 0%,#1c231f00 30%,#1c231f00 45%,#1c231fb3 100%)"}}></div>
            <div style={{position:"absolute",inset:"0",display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"min(2.33rem,6vw) clamp(1rem,5vw,12rem) min(3rem,10vw)"}}>
              <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem"}}>
                <span style={{padding:"0.53rem 0.8rem",borderRadius:"999px",background:"#1c231f66",WebkitBackdropFilter:"blur(6px)",backdropFilter:"blur(6px)",fontSize:"0.8rem",fontWeight:"700",lineHeight:"1"}}>02</span>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",lineHeight:"1"}}>Proposed · DA lodged</span>
              </div>
              <div style={{display:"flex",flexDirection:"column",gap:"1.66rem"}}>
                <span style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea"}}>Brisbane, Queensland</span>
                <span style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(9rem,17vw)",lineHeight:"0.88",letterSpacing:"-0.01em"}}>West End</span>
                <div style={{display:"flex",flexWrap:"wrap",alignItems:"center",justifyContent:"space-between",gap:"1.2rem 2rem",paddingTop:"1.4rem",borderTop:"0.13rem solid #f6f2ea66"}}>
                  <div style={{display:"flex",flexWrap:"wrap",gap:"0.66rem 1.8rem"}}>
                    <span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>113 apartments proposed</span>
                    <span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>13 storeys</span>
                    <span style={{display:"inline-flex",alignItems:"center",gap:"0.66rem"}}><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg>Lodged September 2026</span>
                  </div>
                  <span style={{display:"inline-flex",alignItems:"center",border:"0.13rem solid #f6f2ea",borderRadius:"999px",padding:"0.84em 2.6em",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase"}}>View proposal</span>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </section>

    <section aria-label="Statement" style={{position:"relative",zIndex:"3",background:"#f6f2ea"}}>
      <div style={{position:"relative",zIndex:"1",padding:"min(4.5rem,12vw) 0 min(4.5rem,12vw)",backgroundImage:"linear-gradient(90deg,#6f7e6b,#b9c0aa)",overflow:"hidden"}}>
        <div data-marquee="30" aria-label="Property shaped by experience. Development with a long-term perspective." style={{display:"flex",overflow:"hidden",color:"#f6f2ea"}}>
          <div data-marquee-track="" aria-hidden="true" style={{display:"flex",flex:"none",whiteSpace:"nowrap",paddingRight:"0.5em",fontSize:"min(7.06rem,15vw)",fontWeight:"300",lineHeight:"1.25",textTransform:"uppercase"}}>Property <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>shaped</em> by experience — development with a <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>long-term</em> perspective —</div>
          <div data-marquee-track="" aria-hidden="true" style={{display:"flex",flex:"none",whiteSpace:"nowrap",paddingRight:"0.5em",fontSize:"min(7.06rem,15vw)",fontWeight:"300",lineHeight:"1.25",textTransform:"uppercase"}}>Property <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>shaped</em> by experience — development with a <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>long-term</em> perspective —</div>
        </div>
      </div>
    </section>

    <section aria-labelledby="exp-h" style={{position:"relative",zIndex:"2",background:"#f6f2ea",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)"}}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,26rem),1fr))",gap:"3rem 3.33rem",alignItems:"end"}}>
        <div style={{display:"flex",flexDirection:"column",gap:"1rem"}}>
          <span data-r="fade" style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",letterSpacing:"0.04em"}}>Experience</span>
          <div data-r="lines" aria-label="Around 30 years" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",lineHeight:"0.8",letterSpacing:"-0.03em"}}>
            <span style={{display:"block",overflow:"hidden",padding:"0.02em 0 0.06em"}}><span data-line="" style={{display:"flex",alignItems:"flex-start",gap:"0.06em"}}><span data-count="30" style={{fontSize:"min(24rem,56vw)",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.04em"}}>30</span><span style={{fontSize:"min(4rem,11vw)",color:"#6f7e6b",marginTop:"0.2em",fontStyle:"italic"}}>yrs</span></span></span>
          </div>
        </div>
        <div style={{display:"flex",flexDirection:"column",gap:"2rem",paddingBottom:"1rem"}}>
          <h2 id="exp-h" data-r="lines" style={{margin:"0",fontSize:"min(2.4rem,7.4vw)",fontWeight:"600",lineHeight:"1.12",color:"#1c231f",letterSpacing:"-0.02em"}}>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.04em"}}><span data-line="" style={{display:"block"}}>Around three decades in</span></span>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.04em"}}><span data-line="" style={{display:"block"}}>Brisbane real estate, now</span></span>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.04em"}}><span data-line="" style={{display:"block"}}>applied to development.</span></span>
          </h2>
          <p data-r="fade" style={{margin:"0",maxWidth:"32rem",textWrap:"pretty"}}>Development-industry reporting describes Graham as a long-time Brisbane real-estate agent of around thirty years’ standing. That market knowledge informs the sites, products and projects he takes on through Furtado Property.</p>
          <div data-r="group" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,9rem),1fr))",gap:"1.66rem 2rem"}}>
            <div style={{display:"flex",flexDirection:"column",gap:"0.53rem",paddingTop:"1.33rem",borderTop:"0.13rem solid #6f7e6b40"}}><span data-count="" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",lineHeight:"1",color:"#6f7e6b"}}>20+</span><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",lineHeight:"1.3"}}>Years of property experience — Furtado Property</span></div>
            <div style={{display:"flex",flexDirection:"column",gap:"0.53rem",paddingTop:"1.33rem",borderTop:"0.13rem solid #6f7e6b40"}}><span data-count="" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",lineHeight:"1",color:"#6f7e6b"}}>25</span><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",lineHeight:"1.3"}}>Residences at MIRA Living, Bargara</span></div>
            <div style={{display:"flex",flexDirection:"column",gap:"0.53rem",paddingTop:"1.33rem",borderTop:"0.13rem solid #6f7e6b40"}}><span data-count="" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",lineHeight:"1",color:"#6f7e6b"}}>113</span><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",lineHeight:"1.3"}}>Apartments proposed, West End</span></div>
          </div>
        </div>
      </div>
    </section>

    <section id="expertise" aria-labelledby="skill-h" style={{position:"relative",zIndex:"2",background:"#eee9df",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)"}}>
      <div style={{display:"flex",flexWrap:"wrap",alignItems:"flex-end",justifyContent:"space-between",gap:"1.5rem 3rem",marginBottom:"min(4rem,12vw)"}}>
        <h2 id="skill-h" data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.06rem,11vw)",lineHeight:"0.95"}}>
          <span style={{display:"block",overflow:"hidden",paddingBottom:"0.1em"}}><span data-line="" style={{display:"block",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>Expertise.</span></span>
        </h2>
        <p data-r="fade" style={{margin:"0",maxWidth:"28rem",textWrap:"pretty"}}>The work publicly associated with Graham and Furtado Property follows the full development lifecycle, from site opportunity and strategy to coordination, delivery and market knowledge.</p>
      </div>
      <div data-switch="" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,26rem),1fr))",gap:"2.5rem 3.33rem",alignItems:"start"}}>
        <div data-r="img" style={{position:"sticky",top:"6rem",height:"min(34rem,90vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}>
          <div data-r-inner="" style={{position:"absolute",inset:"0"}}>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.1" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Cleared development site with survey pegs and an excavator, Brisbane suburbs in soft haze behind. Early morning light</span></MediaSlot></div>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.2" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Calm apartment living room, oak floor, stone bench, sheer curtains, sea light. Minimal styling</span></MediaSlot></div>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.3" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Straight-down drone view of a corner residential block with surrounding streets and trees, Brisbane inner suburb</span></MediaSlot></div>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.4" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Leafy Brisbane street: jacaranda, timber Queenslander houses, footpath, late afternoon shadows</span></MediaSlot></div>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.5" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Mid-rise building under construction: formwork, crane, workers in hi-vis, blue sky</span></MediaSlot></div>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.6" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Architect’s desk: floor plans, timber and stone samples, brick, pencil. Overhead shot, neutral palette</span></MediaSlot></div>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.7" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Brisbane skyline from the river at dusk, Story Bridge lights, calm water</span></MediaSlot></div>
            <div data-switch-panel="" style={{position:"absolute",inset:"0"}}><MediaSlot k="svc.8" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Row of contemporary townhouses, brick + timber, landscaped verge, empty street, morning</span></MediaSlot></div>
          </div>
        </div>
        <div data-r="group" style={{display:"flex",flexDirection:"column",borderTop:"0.13rem solid #6f7e6b40"}}>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>01</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Property Development</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Residential development from early opportunity and site stage through design coordination, delivery and market completion.</span></span></span></button>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>02</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Residential Development Strategy</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Project direction, target market, product positioning, development priorities and the residential offer.</span></span></span></button>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>03</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Site Identification &amp; Acquisition</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Recognising locations and sites with potential, and considering market gaps and development fit.</span></span></span></button>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>04</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Development Feasibility</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Early-stage, high-level assessment of market fit, site potential, product direction and development opportunity.</span></span></span></button>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>05</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Development Management</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Coordinating architects, designers, planners, engineers, builders, sales teams and other project specialists.</span></span></span></button>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>06</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Design &amp; Consultant Coordination</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Bringing specialist teams together while holding the development vision and the end-user outcome.</span></span></span></button>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>07</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Property Market Advisory</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Applying long-term real-estate experience to location, buyer, residential-market and product decisions.</span></span></span></button>
          <button type="button" data-switch-item="" aria-expanded="false" style={{display:"block",width:"100%",textAlign:"left",background:"none",border:"0",borderBottom:"0.13rem solid #6f7e6b40",padding:"1.2rem 0",cursor:"pointer",font:"inherit",color:"inherit"}} className="gf-btn gf-btn-switch"><span style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",gap:"1.2rem"}}><span data-switch-num="" style={{display:"flex",alignItems:"center",justifyContent:"center",flex:"none",width:"2.33rem",height:"2.33rem",borderRadius:"999px",background:"#6f7e6b",color:"#f6f2ea",fontSize:"0.9rem",fontWeight:"600",transition:"background-color .4s"}}>08</span><span data-switch-title="" style={{fontSize:"min(1.6rem,5.4vw)",fontWeight:"600",lineHeight:"1.15",color:"#6f7e6b",transition:"color .4s"}}>Real Estate Advisory</span></span></span><span data-switch-desc="" style={{display:"grid",gridTemplateRows:"0fr",opacity:"0",transition:"grid-template-rows .7s cubic-bezier(.25,1,.5,1),opacity .6s"}}><span style={{overflow:"hidden"}}><span style={{display:"block",padding:"0.9rem 0 0.2rem 3.53rem",maxWidth:"34rem",color:"#5f665f"}}>Strategic residential property guidance informed by an extensive real-estate career.</span></span></span></button>
          <a href="/expertise" style={{alignSelf:"flex-start",marginTop:"2rem",display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f",paddingBottom:"0.5rem",background:"linear-gradient(#1c231f,#1c231f) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow gf-btn gf-btn-arrow">All expertise <svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
        </div>
      </div>
    </section>

    <section id="approach" aria-labelledby="app-h" style={{position:"relative",zIndex:"3",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",color:"#f6f2ea",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) calc(min(4.5rem,14vw) + min(4.33rem,12vw))",marginBottom:"calc(-1 * min(4.33rem,12vw))",borderRadius:"0 0 min(4.33rem,12vw) min(4.33rem,12vw)"}}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,26rem),1fr))",gap:"2.5rem 3.33rem",alignItems:"stretch"}}>
        <div style={{display:"flex",flexDirection:"column",justifyContent:"space-between",gap:"1.26rem",maxWidth:"32rem"}}>
          <h2 id="app-h" data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.06rem,11vw)",lineHeight:"0.95",color:"#f6f2ea"}}>
            <span style={{display:"block",overflow:"hidden",paddingBottom:"0.1em"}}><span data-line="" style={{display:"block"}}>Approach.</span></span>
          </h2>
          <p data-r="fade" style={{margin:"0",color:"#f6f2ea",textWrap:"pretty"}}>Furtado Property frames every project as one journey, from finding the right site through to handing over the keys.</p>
          <p data-r="fade" style={{margin:"0",color:"#f6f2ea",textWrap:"pretty"}}>Six stages, one development vision held from start to finish.</p>
          <a data-r="fade" href="/approach" style={{alignSelf:"flex-start",marginTop:"1rem",display:"inline-flex",alignItems:"center",justifyContent:"center",background:"#f6f2ea",color:"#1c231f",borderRadius:"999px",padding:"1.2em 3em",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",transition:"background-color .3s,color .3s"}} className="hv-fill-ink gf-btn gf-btn-cta">The development approach</a>
        </div>
        <div style={{position:"relative",paddingLeft:"min(2rem,4vw)"}}>
          <span data-r="rule" style={{position:"absolute",left:"0",top:"1.3rem",bottom:"1.3rem",width:"0.13rem",background:"#f6f2eab3",transformOrigin:"50% 0%"}}></span>
          <div data-r="group" style={{display:"flex",flexDirection:"column",gap:"0.5rem"}}>
            <a href="/approach" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0.6rem 0.6rem 0.6rem 0.6rem",borderRadius:"999px",border:"0.13rem solid #f6f2eab3",color:"#f6f2ea",transition:"background-color .3s,color .3s,border-color .3s"}} className="hv-pill-light gf-btn gf-btn-row"><span style={{display:"flex",alignItems:"center",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",justifyContent:"center",width:"2.2rem",height:"2.2rem",borderRadius:"999px",background:"#f6f2ea",color:"#1c231f",fontSize:"0.85rem",fontWeight:"600"}}>01</span><span style={{fontSize:"1.15rem",fontWeight:"600"}}>Identify</span></span><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1.1rem",height:"0.7rem",marginRight:"0.6rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
            <a href="/approach" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0.6rem 0.6rem 0.6rem 0.6rem",borderRadius:"999px",border:"0.13rem solid #f6f2eab3",color:"#f6f2ea",transition:"background-color .3s,color .3s,border-color .3s"}} className="hv-pill-light gf-btn gf-btn-row"><span style={{display:"flex",alignItems:"center",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",justifyContent:"center",width:"2.2rem",height:"2.2rem",borderRadius:"999px",background:"#f6f2ea",color:"#1c231f",fontSize:"0.85rem",fontWeight:"600"}}>02</span><span style={{fontSize:"1.15rem",fontWeight:"600"}}>Assess</span></span><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1.1rem",height:"0.7rem",marginRight:"0.6rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
            <a href="/approach" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0.6rem 0.6rem 0.6rem 0.6rem",borderRadius:"999px",border:"0.13rem solid #f6f2eab3",color:"#f6f2ea",transition:"background-color .3s,color .3s,border-color .3s"}} className="hv-pill-light gf-btn gf-btn-row"><span style={{display:"flex",alignItems:"center",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",justifyContent:"center",width:"2.2rem",height:"2.2rem",borderRadius:"999px",background:"#f6f2ea",color:"#1c231f",fontSize:"0.85rem",fontWeight:"600"}}>03</span><span style={{fontSize:"1.15rem",fontWeight:"600"}}>Envision</span></span><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1.1rem",height:"0.7rem",marginRight:"0.6rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
            <a href="/approach" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0.6rem 0.6rem 0.6rem 0.6rem",borderRadius:"999px",border:"0.13rem solid #f6f2eab3",color:"#f6f2ea",transition:"background-color .3s,color .3s,border-color .3s"}} className="hv-pill-light gf-btn gf-btn-row"><span style={{display:"flex",alignItems:"center",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",justifyContent:"center",width:"2.2rem",height:"2.2rem",borderRadius:"999px",background:"#f6f2ea",color:"#1c231f",fontSize:"0.85rem",fontWeight:"600"}}>04</span><span style={{fontSize:"1.15rem",fontWeight:"600"}}>Design</span></span><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1.1rem",height:"0.7rem",marginRight:"0.6rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
            <a href="/approach" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0.6rem 0.6rem 0.6rem 0.6rem",borderRadius:"999px",border:"0.13rem solid #f6f2eab3",color:"#f6f2ea",transition:"background-color .3s,color .3s,border-color .3s"}} className="hv-pill-light gf-btn gf-btn-row"><span style={{display:"flex",alignItems:"center",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",justifyContent:"center",width:"2.2rem",height:"2.2rem",borderRadius:"999px",background:"#f6f2ea",color:"#1c231f",fontSize:"0.85rem",fontWeight:"600"}}>05</span><span style={{fontSize:"1.15rem",fontWeight:"600"}}>Develop</span></span><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1.1rem",height:"0.7rem",marginRight:"0.6rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
            <a href="/approach" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0.6rem 0.6rem 0.6rem 0.6rem",borderRadius:"999px",border:"0.13rem solid #f6f2eab3",color:"#f6f2ea",transition:"background-color .3s,color .3s,border-color .3s"}} className="hv-pill-light gf-btn gf-btn-row"><span style={{display:"flex",alignItems:"center",gap:"1rem"}}><span style={{display:"flex",alignItems:"center",justifyContent:"center",width:"2.2rem",height:"2.2rem",borderRadius:"999px",background:"#f6f2ea",color:"#1c231f",fontSize:"0.85rem",fontWeight:"600"}}>06</span><span style={{fontSize:"1.15rem",fontWeight:"600"}}>Deliver</span></span><svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1.1rem",height:"0.7rem",marginRight:"0.6rem"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a>
          </div>
        </div>
      </div>
    </section>

  </main>

  <SiteFooter />
</div>
  );
}
