import { MediaSlot } from "@/components/media/MediaSlot";
import SiteFooter from "@/components/SiteFooter";
import { pageMeta } from "@/data/siteContent";

export const metadata = pageMeta.expertise;

export default function Page() {
  return (
<div id="top" data-screen-label="Expertise" style={{position:"relative",background:"#f6f2ea"}}>
  <main>

    <section data-hero="" aria-label="Expertise" style={{position:"relative",zIndex:"1"}}>
      <div style={{position:"relative",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",clipPath:"inset(0 round 0 0 min(4.33rem,12vw) min(4.33rem,12vw))"}}>
        <div data-hero-mask="" style={{position:"fixed",top:"0",left:"0",width:"100%",height:"100vh",WebkitMaskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)",maskImage:"linear-gradient(0deg,rgb(0 0 0 / var(--bot,1)) 0%,rgb(0 0 0 / var(--top,1)) 100%)"}}>
          <div data-intro-img="" style={{position:"absolute",inset:"0",transformOrigin:"50% 65%"}}><MediaSlot k="exp.hero" eager style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",right:"clamp(1rem,5vw,12rem)",top:"auto",bottom:"1.5rem",textAlign:"right",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(22rem,60vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>HERO · LANDSCAPE 16:9 · Mid-rise residential project under construction at sunrise, scaffold and crane silhouetted, Brisbane skyline distant</span></MediaSlot></div>
          <div style={{position:"absolute",inset:"0 0 auto 0",height:"13.33rem",backgroundImage:"linear-gradient(#0006,#0000)"}}></div>
          <div style={{position:"absolute",inset:"auto 0 0 0",height:"55%",backgroundImage:"linear-gradient(#1c231f00,#1c231f99)"}}></div>
        </div>
        <div style={{position:"relative",zIndex:"1",height:"100svh",minHeight:"34rem",display:"flex",flexDirection:"column",justifyContent:"flex-end",padding:"0 clamp(1rem,5vw,12rem) min(5rem,16vw)"}}>
          <div style={{display:"flex",flexWrap:"wrap",alignItems:"flex-end",justifyContent:"space-between",gap:"2rem 3rem"}}>
            <div style={{display:"flex",flexDirection:"column",gap:"1.4rem",minWidth:"0"}}>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Expertise</span>
              <h1 style={{margin:"0",color:"#f6f2ea",textTransform:"uppercase",fontWeight:"300",fontSize:"min(7rem,12.5vw,12.5vh)",lineHeight:"0.95",letterSpacing:"-0.03em"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.07em"}}><span data-intro-line="" style={{display:"block"}}>From opportunity</span></span><span style={{display:"block",overflow:"hidden",paddingBottom:"0.07em"}}><span data-intro-line="" style={{display:"block"}}>to <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.08em"}}>delivery.</em></span></span></h1>
            </div>
            <div style={{display:"flex",flexDirection:"column",gap:"0.55rem",paddingBottom:"0.6rem",minWidth:"14rem"}}>
              <span data-intro-fade="" style={{display:"block",height:"0.13rem",width:"3rem",background:"#f6f2eab3",marginBottom:"0.6rem"}}></span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Development</span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Strategy</span>
              <span data-intro-fade="" style={{fontSize:"0.8rem",fontWeight:"700",lineHeight:"1",textTransform:"uppercase",color:"#f6f2ea"}}>Advisory</span>
              <span data-intro-fade="" style={{fontSize:"0.9rem",fontWeight:"500",color:"#b9c0aa",marginTop:"0.4rem"}}>Eight areas of expertise</span>
            </div>
          </div>
          <div style={{position:"absolute",left:"0",right:"0",bottom:"1.4rem",display:"flex",justifyContent:"center",pointerEvents:"none"}}>
            <a href="#intro" aria-label="Scroll down" data-intro-fade="" style={{pointerEvents:"auto",display:"flex",alignItems:"center",justifyContent:"center",width:"2.66rem",height:"2.66rem",color:"#f6f2ea",overflow:"hidden"}}><svg viewBox="0 0 10 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"0.66rem",height:"1.2rem",animation:"arrowLoop 2.6s cubic-bezier(.5,1,.89,1) infinite"}}><path d="M5 1v14M1 10.5L5 15l4-4.5"></path></svg></a>
          </div>
        </div>
        <div id="intro" data-hero-content="" style={{position:"relative",zIndex:"1",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(5.5rem,16vw)",display:"flex",flexDirection:"column",gap:"min(2rem,7vw)"}}><span data-r="fade" style={{fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#f6f2ea",letterSpacing:"0.04em"}}>Services</span><h2 data-r="lines" style={{margin:"0",color:"#f6f2ea",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.6rem,7.2vw)",lineHeight:"1.04",letterSpacing:"-0.02em",maxWidth:"80rem"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>The residential development</span></span><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>lifecycle, <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",fontSize:"1.08em"}}>end to end.</em></span></span></h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,24rem),1fr))",gap:"2rem 3.33rem",alignItems:"end"}}><p data-r="fade" style={{margin:"0",color:"#f6f2ea",fontSize:"1.13rem",lineHeight:"1.45",maxWidth:"36rem",textWrap:"pretty"}}>The areas below reflect work publicly associated with Graham and Furtado Property, from site opportunity and strategy to coordination, delivery and market knowledge.</p><div data-r="fade" data-delay="0.15" style={{display:"flex",flexDirection:"column",gap:"1.2rem"}}><p style={{margin:"0",color:"#f6f2ea",fontSize:"0.9rem",maxWidth:"30rem",textWrap:"pretty"}}>Architecture, engineering, town planning and construction are delivered by specialist consultants engaged on each project.</p></div></div></div>
      </div>
    </section><section id="services" style={{position:"relative",zIndex:"2",background:"#f6f2ea",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)"}}><div style={{display:"flex",flexDirection:"column",gap:"min(6.86rem,20vw)"}}><div style={{display:"flex",flexWrap:"wrap",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.1" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Cleared development site with survey pegs and an excavator, Brisbane suburbs in soft haze behind. Early morning light</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>01</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Property Development</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>Residential development from early opportunity and site stage through design coordination, delivery and market completion.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>Demonstrated through MIRA Living in Bargara and the West End proposal in Brisbane.</span></div>
  </div>
</div><div style={{display:"flex",flexWrap:"wrap",flexDirection:"row-reverse",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.2" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.1) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Calm apartment living room, oak floor, stone bench, sheer curtains, sea light. Minimal styling</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>02</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Residential Development Strategy</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>Project direction, target market, product positioning, development priorities and the residential offer.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>MIRA Living is positioned as premium, owner-occupier oriented coastal living.</span></div>
  </div>
</div><div style={{display:"flex",flexWrap:"wrap",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.3" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Straight-down drone view of a corner residential block with surrounding streets and trees, Brisbane inner suburb</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>03</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Site Identification &amp; Acquisition</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>Recognising locations and sites with potential, considering market gaps and development fit.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>Furtado Property’s process begins with finding the right site before a project progresses.</span></div>
  </div>
</div><div style={{display:"flex",flexWrap:"wrap",flexDirection:"row-reverse",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.4" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Leafy Brisbane street: jacaranda, timber Queenslander houses, footpath, late afternoon shadows</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>04</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Development Feasibility</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>High-level, early-stage assessment of market fit, site potential, product direction and development opportunity.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>Informed by around three decades in the Brisbane property market.</span></div>
  </div>
</div></div></section><section aria-label="Site, strategy, coordination, delivery" style={{position:"relative",zIndex:"2",backgroundImage:"linear-gradient(90deg,#6f7e6b,#b9c0aa)",padding:"1rem 0",overflow:"hidden"}}><div data-marquee="26" style={{display:"flex",overflow:"hidden",color:"#f6f2ea"}}><div data-marquee-track="" aria-hidden="true" style={{display:"flex",flex:"none",whiteSpace:"nowrap",paddingRight:"0.5em",fontSize:"min(7.06rem,15vw)",fontWeight:"300",lineHeight:"1.25",textTransform:"uppercase"}}>Site <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em> Strategy <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em> Coordination <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em> Delivery <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em></div><div data-marquee-track="" aria-hidden="true" style={{display:"flex",flex:"none",whiteSpace:"nowrap",paddingRight:"0.5em",fontSize:"min(7.06rem,15vw)",fontWeight:"300",lineHeight:"1.25",textTransform:"uppercase"}}>Site <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em> Strategy <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em> Coordination <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em> Delivery <em style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"300",fontSize:"1.06em",margin:"0 0.25em"}}>·</em></div></div></section><section id="services-2" style={{position:"relative",zIndex:"2",background:"#f6f2ea",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)"}}><div style={{display:"flex",flexDirection:"column",gap:"min(6.86rem,20vw)"}}><div style={{display:"flex",flexWrap:"wrap",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.5" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.1) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Mid-rise building under construction: formwork, crane, workers in hi-vis, blue sky</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>05</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Development Management</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>Coordinating architects, designers, planners, engineers, builders, sales teams and other project specialists.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>West End brings together architecture, town planning, landscape, traffic and civil consultants.</span></div>
  </div>
</div><div style={{display:"flex",flexWrap:"wrap",flexDirection:"row-reverse",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.6" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.05) 0 1px,transparent 1px 16px),linear-gradient(160deg,#6b7767 0%,#4a544c 60%,#1c231f 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Architect’s desk: floor plans, timber and stone samples, brick, pencil. Overhead shot, neutral palette</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>06</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Design &amp; Consultant Coordination</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>Bringing specialist teams together while holding the development vision and the end-user outcome.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>Furtado Property partners with experienced architects and designers.</span></div>
  </div>
</div><div style={{display:"flex",flexWrap:"wrap",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.7" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.07) 0 1px,transparent 1px 16px),linear-gradient(160deg,#cfd2bf 0%,#a9b19c 55%,#6f7e6b 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#f6f2ea",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Brisbane skyline from the river at dusk, Story Bridge lights, calm water</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>07</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Property Market Advisory</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>Applying long-term real-estate experience to location, buyer, residential-market and product decisions.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>Around thirty years as a Brisbane real-estate agent.</span></div>
  </div>
</div><div style={{display:"flex",flexWrap:"wrap",flexDirection:"row-reverse",alignItems:"center",gap:"min(2.4rem,7vw) 3.33rem"}}>
  <div style={{flex:"1 1 26rem",minWidth:"0"}}><div data-r="img" data-parallax="6" style={{position:"relative",height:"min(32rem,100vw)",borderRadius:"1rem",overflow:"hidden",background:"#b9c0aa"}}><div data-r-inner="" style={{position:"absolute",inset:"0"}}><div data-parallax-inner="" style={{position:"absolute",inset:"-10% 0"}}><MediaSlot k="svc.8" style={{position:"absolute",inset:"0",backgroundImage:"repeating-linear-gradient(135deg,rgba(246,242,234,0.1) 0 1px,transparent 1px 16px),linear-gradient(160deg,#ece7dc 0%,#d3d5c3 60%,#b9c0aa 100%)"}}><span data-ph-label="" style={{position:"absolute",left:"1.33rem",bottom:"1.33rem",font:"600 0.66rem/1.3 ui-monospace,Menlo,monospace",letterSpacing:"0.02em",textTransform:"none",color:"#5f665f",maxWidth:"min(26rem,70vw)",fontSize:"0.72rem",lineHeight:"1.45",textWrap:"pretty"}}>SQUARE-ISH 4:5 · Row of contemporary townhouses, brick + timber, landscaped verge, empty street, morning</span></MediaSlot></div></div></div></div>
  <div style={{flex:"1 1 26rem",minWidth:"0",display:"flex",flexDirection:"column",gap:"1rem",maxWidth:"34rem"}}>
    <span data-r="fade" style={{fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontSize:"min(3.06rem,11vw)",color:"#6f7e6b",lineHeight:"1"}}>08</span>
    <h3 data-r="lines" style={{margin:"0",fontSize:"min(1.8rem,6.4vw)",fontWeight:"600",lineHeight:"1.2",color:"#1c231f"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.06em"}}><span data-line="" style={{display:"block"}}>Real Estate Advisory</span></span></h3>
    <p data-r="fade" style={{margin:"0",textWrap:"pretty"}}>Strategic residential property guidance informed by an extensive real-estate career.</p><div data-r="fade" style={{display:"grid",gridTemplateColumns:"7rem minmax(0,1fr)",gap:"1rem",paddingTop:"1rem",marginTop:"0.5rem",borderTop:"0.13rem solid #6f7e6b40"}}><span style={{fontSize:"0.72rem",fontWeight:"700",textTransform:"uppercase",color:"#6f7e6b",paddingTop:"0.2rem"}}>In practice</span><span style={{fontWeight:"600",color:"#1c231f",textWrap:"pretty"}}>Grounded in long-standing experience across the Brisbane residential market.</span></div>
  </div>
</div></div></section><section style={{position:"relative",zIndex:"2",background:"#eee9df",padding:"min(4.5rem,14vw) clamp(1rem,5vw,12rem) min(4.8rem,15vw)",paddingBottom:"min(5rem,16vw)"}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,24rem),1fr))",gap:"min(2.4rem,7vw) 3.33rem",alignItems:"end"}}><div style={{display:"flex",flexDirection:"column",gap:"1.66rem",minWidth:"0"}}><h2 id="dp-h" data-r="lines" style={{margin:"0",fontFamily:"var(--font-inria),serif",fontStyle:"italic",fontWeight:"400",textTransform:"uppercase",fontSize:"min(3.06rem,11vw)",lineHeight:"0.95"}}><span style={{display:"block",overflow:"hidden",paddingBottom:"0.1em"}}><span data-line="" style={{display:"block",backgroundImage:"linear-gradient(15deg,#6f7e6b,#b9c0aa)",WebkitBackgroundClip:"text",backgroundClip:"text",WebkitTextFillColor:"transparent",paddingRight:"0.08em"}}>Discuss a project.</span></span></h2></div><div style={{display:"flex",flexDirection:"column",gap:"1.66rem",minWidth:"0"}}><p data-r="fade" style={{margin:"0",textWrap:"pretty",fontSize:"1.13rem",lineHeight:"1.45",color:"#1c231f",maxWidth:"36rem"}}>For development, site and residential property enquiries, get in touch with Graham directly.</p><a href="/contact" style={{alignSelf:"flex-start",display:"inline-flex",alignItems:"center",gap:"0.9rem",fontSize:"0.8rem",fontWeight:"700",textTransform:"uppercase",color:"#1c231f",paddingBottom:"0.5rem",background:"linear-gradient(#1c231f,#1c231f) 0 100%/100% 0.13rem no-repeat",transition:"gap .6s cubic-bezier(.25,1,.5,1),color .3s"}} className="hv-arrow gf-btn gf-btn-arrow">Contact <svg viewBox="0 0 16 10" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{width:"1rem",height:"0.66rem",flex:"none"}}><path d="M1 5h14M10.5 1L15 5l-4.5 4"></path></svg></a></div></div></section>
  </main>
  <SiteFooter showContact={false} />
</div>
  );
}
